# Prometheus Configuration for LLM Gateway
# =========================================
# Place in /etc/prometheus/prometheus.yml or mount in Docker

global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # LLM Gateway metrics
  - job_name: 'llm-gateway'
    static_configs:
      - targets: ['gateway:8000']
    metrics_path: '/metrics'
    scheme: 'http'
    # Add basic auth if needed
    # basic_auth:
    #   username: 'prometheus'
    #   password_file: '/etc/prometheus/gateway_password'

  # Node exporter (optional, for system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
